src/objects/Attendance__c.object
<CustomObject>
    <fields>
        <fullName>Confirmed_By__c</fullName>
        <label>Confirmed By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Confirmed_By</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CutOff__c</fullName>
        <label>CutOff</label>
        <referenceTo>CutOff__c</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In</fullName>
                </value>
                <value>
                    <fullName>Half-Day</fullName>
                </value>
                <value>
                    <fullName>Off</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attendance</label>
    <nameField>
        <displayFormat>SA - {0000000}</displayFormat>
        <label>Attendance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CutOff__c.object
<CustomObject>
    <fields>
        <fullName>Confirmed_By__c</fullName>
        <label>Confirmed By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Confirmed_By</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End__c</fullName>
        <label>End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <label>Start</label>
        <type>Date</type>
    </fields>
    <label>CutOff</label>
    <nameField>
        <displayFormat>CO - {00000}</displayFormat>
        <label>CutOff ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CuttOffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <label>Full_Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <displayFormat>Staff - {00}</displayFormat>
        <label>Staff ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Confirmed_By.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Not Confirmed</fullName>
        <default>true</default>
        <label>Not Confirmed</label>
    </customValue>
    <customValue>
        <fullName>Thess</fullName>
    </customValue>
    <customValue>
        <fullName>Lui</fullName>
    </customValue>
    <customValue>
        <fullName>Anna</fullName>
    </customValue>
    <masterLabel>Confirmed By</masterLabel>
</GlobalValueSet>

src/classes/AttendanceController.cls
public class AttendanceController{
    
    public date SelectedDate { get; set; }
    public void setSelectedDate(){
        Integer m= Integer.valueOf( Apexpages.currentPage().getParameters().get('m'));
        Integer d= Integer.valueOf( Apexpages.currentPage().getParameters().get('d'));
        Integer y= Integer.valueOf( Apexpages.currentPage().getParameters().get('y'));
        Selecteddate = DateTime.NewInstance(y,m,d,0,0,0).Date();
    }
    
    public class DTO_Attendance{
        public Integer day { get{
            return attendance.Date__c.day();
        }}
        public Attendance__c attendance { get; set; }
    }
    
    public Integer monthDays {
        get{
            if (selectedYear==2016 && selectedMonth==2)
               return 29;
           return BodyTechUtil.getMonthDays(selectedMonth);
        }
    }
    
    public List<Staff__c> getStaffs(){
        return [Select Id, Full_Name__c, Name__c, Alias__c, Active__c from Staff__c where Active__c=true];
    }
    
    public Integer selectedYear { get; set; }
    public Integer selectedMonth { get; set; }
    public List<DTO_Attendance> attendanceList { get; set; }
    public Attendance__c att { get; set; }
    public AttendanceController(){
        Date today = System.Today();
        selectedMonth = today.month();
        selectedYear = today.year();
        getAttendance(selectedYear, selectedMonth);
    }
    public void getAttendance(Integer y, Integer m){
        List<Attendance__c> l= [Select Id, Name, Date__c, Note__c, Staff__r.Id, Staff__r.Alias__c, Staff__r.Name__c, 
                    Type__c, Confirmed_By__c from Attendance__c where Calendar_Month(Date__c)=:m and Calendar_Year(Date__c)=:y];
        List<DTO_Attendance> dto = new List<DTO_Attendance>();
        for(Attendance__c a : l){
            DTO_Attendance x = new DTO_Attendance();
            x.attendance = a;
            dto.add(x);
        }
        selectedMonth = m;
        selectedYear = y;
        attendanceList  = dto;
        
    }
    public void saveAttendance(){
        upsert att;
    }
    
    public void upsertAttendance(){
        Integer day = Integer.valueOf( Apexpages.currentPage().getParameters().get('day'));
        
        string status=  Apexpages.currentPage().getParameters().get('status');
        string staffId=  Apexpages.currentPage().getParameters().get('staffId');
    
        Date d = dateTime.newInstance(selectedyear, selectedmonth, day,0,0,0).date();
        List<Attendance__c> att = [Select Id, Type__c, Date__c, Staff__c, Confirmed_By__c  from Attendance__c where Staff__c=:staffId and Date__c=:d];
        Attendance__c a = null;
        if(att.size()>0){
            a= att[0];   
            
        }else
            a= new Attendance__c();
        a.Type__c = status;
        a.Staff__c = staffId;
        a.Date__c = d;
        String cutOffId = '';
        for(cutOff__c c : [Select Id, Start__c, End__c from CutOff__c]){
            if(c.Start__c<=d && d<=c.End__c){
                cutOffId=c.Id;
                break;
            }
        }
        
        if(cutOffId!='' && a.Id==null){
            a.cutOff__c = cutOffId;   
        }
        upsert a;
    }
    
     public void getMonthlyAttendance(){
        Integer y = Integer.valueOf( Apexpages.currentPage().getParameters().get('y'));
        Integer m= Integer.valueOf( Apexpages.currentPage().getParameters().get('m'));
        Date today = System.Today();
        getAttendance(y,m);
        
     }

}