src/objects/Attendance__c.object
<CustomObject>
    <fields>
        <fullName>Confirmed_By__c</fullName>
        <label>Confirmed By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Confirmed_By</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CutOff__c</fullName>
        <label>CutOff</label>
        <referenceTo>CutOff__c</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In</fullName>
                </value>
                <value>
                    <fullName>Half-Day</fullName>
                </value>
                <value>
                    <fullName>Off</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attendance</label>
    <nameField>
        <displayFormat>SA - {0000000}</displayFormat>
        <label>Attendance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Cash_Advance__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Cash Advances</relationshipLabel>
        <relationshipName>Cash_Advances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Cash Advance</label>
    <nameField>
        <displayFormat>CA-{0000000}</displayFormat>
        <label>Cash Advance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Advances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CutOff__c.object
<CustomObject>
    <fields>
        <fullName>Confirmed_By__c</fullName>
        <label>Confirmed By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Confirmed_By</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End__c</fullName>
        <label>End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <label>Start</label>
        <type>Date</type>
    </fields>
    <label>CutOff</label>
    <nameField>
        <displayFormat>CO - {00000}</displayFormat>
        <label>CutOff ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CuttOffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <displayFormat>Staff - {00}</displayFormat>
        <label>Staff ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Confirmed_By.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Not Confirmed</fullName>
        <default>true</default>
        <label>Not Confirmed</label>
    </customValue>
    <customValue>
        <fullName>Thess</fullName>
    </customValue>
    <customValue>
        <fullName>Lui</fullName>
    </customValue>
    <customValue>
        <fullName>Anna</fullName>
    </customValue>
    <masterLabel>Confirmed By</masterLabel>
</GlobalValueSet>

src/classes/CutOffController.cls
public class CutOffController{

    public class CutOffSummary { 
        public List<StaffCutOffSummary> staffSummaryList { get; set; }
        public CutOff__c cutOff { get; set; }
        public string Confirmed_By { get; set; }
    }
    
    public String SelectCutOffId { get; set; }
    public void setSelectedCutOff(){
    }
    
    public class StaffCutOffSummary{
        public Staff__c Staff { get; set; }
        public CutOff__c CutOff { get; set; }
        public decimal grossSalary { get; set; }
        public decimal pastBalance { get; set; }
        public List<Cash_Advance__c> advances { get; set; }
        public List<Attendance__c> attendance { get; set; }
        
    }

    public CutOffSummary summary{ get; set; }
    public List<Staff__c> staffs { get; set; }
    public CutOffController(){
        //
        //getAllCutOffSummaries();
    }
    
    public void getStaffs(){
        staffs=  [Select Id, Alias__c, Name__c from Staff__c where Active__c=true];
    }
    
    public List<CutOffSummary> AllCutOffSummaries { get; set; }
    
    public Pagereference getAllCutOffSummaries(){
        getStaffs();
        AllCutOffSummaries = new List<CutOffSummary>();
        
        List<CutOff__c> cutOffs = [Select Id, Start__c, End__c, Confirmed_By__c from CutOff__c order by End__c desc];
        
        
        List<StaffCutOffSummary> staffSummaryList = new List<StaffCutOffSummary>();
        
        
        Map<Id, List<Attendance__c>> cutOffAttendance = new Map<Id, List<Attendance__c>>();
        
        for(Attendance__c a : [Select Id, Staff__c, Staff__r.Alias__c, Type__c, Date__c, CutOff__c, CutOff__r.Confirmed_By__c  from Attendance__c]){
            if(cutOffAttendance.ContainsKey(a.CutOff__c)){
                List<Attendance__c> att = cutoffAttendance.get(a.cutOff__c);
                att.add(a);
                cutOffAttendance.put(a.cutOff__c, att);
            }else{
                cutOffAttendance.put(a.cutOff__c, new List<Attendance__c>{ a} );
            }
        }
        
        
        List<Date> plus50= new List<Date>();
        List<Date> doublePay = new List<Date>();
        doublePay.add(dateTime.newInstance(2015,12,25,0,0,0).date());
        doublePay.add(dateTime.newInstance(2015,12,31,0,0,0).date());
        doublePay.add(dateTime.newInstance(2016,1,1,0,0,0).date());
        
        for(Integer i=20; i<=31;i++){
            plus50.add(dateTime.newInstance(2015,12,i,0,0,0).date());
        }
        plus50.add(dateTime.newInstance(2016,1,1,0,0,0).date());
        
        
        
        for(CutOff__c c : cutOffs){
            CutOffSummary mSummary= new CutOffSummary();  
            mSummary.cutOff=c; 
            mSummary.Confirmed_By = c.Confirmed_By__c;         
            for(Staff__c a : staffs){
                decimal baseSalary=100;
                decimal grossSalary = 0;
                List<Attendance__c> att = new List<Attendance__c>();
                StaffCutOffSummary s = new StaffCutOffSummary();
                s.cutoff= c;
                s.staff= a;
                
                List<Attendance__c> attList = cutOffAttendance.get(c.Id);
                if(attList!=null){
                    for(Attendance__c at : attList){
                    boolean mdoublePay=false;
                    boolean mplus50=false;
                    if(at.Staff__c == a.Id){
                        att.add(at);
                        for(Date dt : doublePay){
                            if(dt==at.Date__c){
                                mdoublePay=true;
                                break;
                            }                                
                        }
                        for(Date dt : plus50){
                            if(dt==at.Date__c){
                                mplus50=true;
                                break;
                            }                                
                        }
                        
                        if(mdoublePay){
                            if(mplus50){
                                baseSalary = 300;
                            }else{
                                baseSalary = 200;
                            }
                        }else{
                            if(mplus50)
                                baseSalary=150;
                            else
                                baseSalary=100;
                        }
                        
                        if(a.Id=='a0c90000008tJ0c'){
                            date d1 = dateTime.newInstance(2016,1,5).date();
                            date d2 = dateTime.newInstance(2016,1,10).date();
                            date d3 = dateTime.newInstance(2016,1,11).date();
                            if(at.date__c<=d2 && at.date__c>=d1)
                                baseSalary = 200;
                            else if (at.date__c>=d3)
                                baseSalary=250;
                            
                        }
                        
                        if(at.Type__c=='In')
                            grossSalary+=baseSalary;
                        if(at.Type__c=='Half-Day')
                            grossSalary+=(baseSalary/2);
                        //break;                      
                    }
                }                
                }
                s.grossSalary= grossSalary;
                s.attendance = att;                
                staffSummaryList.add(s);
            }
            
            
            mSummary.staffSummaryList=staffSummaryList;
            
            AllCutOffSummaries.add(mSummary);
        }
        
        System.debug('cutOffSummaries :'+AllCutOffSummaries);
        return null;
        //return cutOffSummaries;
    }
    
    
}