src/objects/Attendance__c.object
<CustomObject>
    <fields>
        <fullName>Confirmed_By__c</fullName>
        <label>Confirmed By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Confirmed_By</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CutOff__c</fullName>
        <label>CutOff</label>
        <referenceTo>CutOff__c</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In</fullName>
                </value>
                <value>
                    <fullName>Half-Day</fullName>
                </value>
                <value>
                    <fullName>Off</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attendance</label>
    <nameField>
        <displayFormat>SA - {0000000}</displayFormat>
        <label>Attendance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Client_Service__c.object
<CustomObject>
    <fields>
        <fullName>Confirmed_By__c</fullName>
        <label>Confirmed By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Confirmed_By</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Time__c</fullName>
        <label>Date Time</label>
        <type>Date</type>
    </fields>
    <label>Client Service</label>
    <nameField>
        <displayFormat>CS-{0000000}</displayFormat>
        <label>Client Service ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CutOff__c.object
<CustomObject>
    <fields>
        <fullName>Confirmed_By__c</fullName>
        <label>Confirmed By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Confirmed_By</valueSetName>
        </valueSet>
    </fields>
    <label>CutOff</label>
    <nameField>
        <displayFormat>CO - {00000}</displayFormat>
        <label>CutOff ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CuttOffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Confirmed_By__c</fullName>
        <label>Confirmed By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Confirmed_By</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Spa Supply</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Operation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>EXP - {0000000}</displayFormat>
        <label>Expense ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Sale__c.object
<CustomObject>
    <fields>
        <fullName>Confirmed_By__c</fullName>
        <label>Confirmed By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Confirmed_By</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sale</fullName>
                    <default>true</default>
                    <label>Sale</label>
                </value>
                <value>
                    <fullName>Clinic Use</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Sale</label>
    <nameField>
        <displayFormat>PS - {0000000}</displayFormat>
        <label>Product Sale ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Confirmed_By.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Not Confirmed</fullName>
        <default>true</default>
        <label>Not Confirmed</label>
    </customValue>
    <customValue>
        <fullName>Thess</fullName>
    </customValue>
    <customValue>
        <fullName>Lui</fullName>
    </customValue>
    <customValue>
        <fullName>Anna</fullName>
    </customValue>
    <masterLabel>Confirmed By</masterLabel>
</GlobalValueSet>

src/classes/ConfirmController.cls
public class ConfirmController{
    
    public string type { get; set; }
    public string objectType { get; set; }
    public Date dateStr { get; set; }
    public string confirmed_by{ get; set; }
    public string recordId  { get; set; }
    
    public void confirm(){
        if(type!=null){
            if (type=='day'){                
                if(objectType=='client_service'){
                    List<Client_Service__c> services = [Select Id, Confirmed_By__c from Client_Service__c where date_Time__c =: dateStr ];
                    for(Client_Service__c cs : services){
                        cs.Confirmed_By__c = confirmed_by;
                    }
                    update services;
                }
                else if(objectType=='expense'){
                    List<Expense__c> expenses= [Select Id, Confirmed_By__c from Expense__c where date__c =: dateStr ];
                    for(Expense__c e : expenses){
                        e.Confirmed_By__c = confirmed_by;
                    }
                    update expenses;
                }
                else if(objectType=='product_sale'){
                    List<Product_sale__c> sales= [Select Id, Confirmed_By__c from Product_sale__c where date__c =: dateStr and Type__c='Sale' ];
                    for(Product_sale__c e : sales){
                        e.Confirmed_By__c = confirmed_by;
                    }
                    update sales;
                }
                else if(objectType=='clinic_use'){
                    List<Product_sale__c> sales= [Select Id, Confirmed_By__c from Product_sale__c where date__c =: dateStr and Type__c='Clinic Use' ];
                    for(Product_sale__c e : sales){
                        e.Confirmed_By__c = confirmed_by;
                    }
                    update sales;
                }
                else if(objectType=='attendance'){
                    List<Attendance__c > data= [Select Id, Confirmed_By__c from Attendance__c where date__c =: dateStr];
                    for(Attendance__c e : data){
                        e.Confirmed_By__c = confirmed_by;
                    }
                    update data;
                }
            }else if(type=='record'){
                if(objectType=='cutoff'){
                    List<CutOff__c> cs = [Select Id, Confirmed_By__c from CutOff__c where Id =: recordId  ];
                    if(cs.size()>0){
                        cs[0].Confirmed_By__c = confirmed_by;
                        update cs[0];
                    }
                }
            }
        }
    }
}