src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Client</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Client_Service__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Client Services</relationshipLabel>
        <relationshipName>Client_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Confirmed_By__c</fullName>
        <label>Confirmed By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Confirmed_By</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Time__c</fullName>
        <label>Date Time</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Client Services</relationshipLabel>
        <relationshipName>Client_Services</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Client Service</label>
    <nameField>
        <displayFormat>CS-{0000000}</displayFormat>
        <label>Client Service ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Confirmed_By__c</fullName>
        <label>Confirmed By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Confirmed_By</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Spa Supply</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Operation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>EXP - {0000000}</displayFormat>
        <label>Expense ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Commission__c</fullName>
        <label>Commission</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <displayFormat>PROD-{0000}</displayFormat>
        <label>Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Sale__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>IF(ISPICKVAL(Type__c,&quot;Clinic Use&quot;), 0, Product__r.Retail_Price__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Confirmed_By__c</fullName>
        <label>Confirmed By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Confirmed_By</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Final_Amount__c</fullName>
        <formula>IF(IsPickVal(Type__c,&quot;Clinic Use&quot;), 0, Amount__c -  Discount__c - Product__r.Commission__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Final Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product Sales</relationshipLabel>
        <relationshipName>Product_Sales</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Product Sales</relationshipLabel>
        <relationshipName>Product_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sale</fullName>
                    <default>true</default>
                    <label>Sale</label>
                </value>
                <value>
                    <fullName>Clinic Use</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Sale</label>
    <nameField>
        <displayFormat>PS - {0000000}</displayFormat>
        <label>Product Sale ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service__c.object
<CustomObject>
    <fields>
        <fullName>Commission__c</fullName>
        <label>Commission</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Type</label>
        <referenceTo>Service_Type__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Service ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Type__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Service Type</label>
    <nameField>
        <displayFormat>ST-{00}</displayFormat>
        <label>Service Type ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Staff__c.object
<CustomObject>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <displayFormat>Staff - {00}</displayFormat>
        <label>Staff ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Staff_Commission__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Client_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Service</label>
        <referenceTo>Client_Service__c</referenceTo>
        <relationshipLabel>Staff Commissions</relationshipLabel>
        <relationshipName>Staff_Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>IF( Product_Sale__c != null, Product_Sale__r.Date__c, Client_Service__r.Date_Time__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Sale__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Sale</label>
        <referenceTo>Product_Sale__c</referenceTo>
        <relationshipLabel>Staff Commissions</relationshipLabel>
        <relationshipName>Staff_Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Staff Commissions</relationshipLabel>
        <relationshipName>Staff_Commissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Staff Commission</label>
    <nameField>
        <displayFormat>SC-{0000000}</displayFormat>
        <label>Staff Commission ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Confirmed_By.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Not Confirmed</fullName>
        <default>true</default>
        <label>Not Confirmed</label>
    </customValue>
    <customValue>
        <fullName>Thess</fullName>
    </customValue>
    <customValue>
        <fullName>Lui</fullName>
    </customValue>
    <customValue>
        <fullName>Anna</fullName>
    </customValue>
    <masterLabel>Confirmed By</masterLabel>
</GlobalValueSet>

src/classes/DailySummaryController.cls
public class DailySummaryController{
    
    public DailySummaryController(){
        Date today = System.today();
        selectedMonth =today.month();
        selectedYear = today.year();
    }
    
    public class DailySummaryList{
        public List<DailySummary> summaryList { get; set; }
        public Integer count{ get{
                if(summaryList==null)
                    return 0;
                Integer c=0;
                for(DailySummary d : summaryList){
                    c+= d.serviceCount;
                }
                return c;
            }
        }
        public decimal totalNetService { get{
            if(summaryList != null){
                decimal v = 0;
                for(DailySummary d : summaryList){
                    v += d.netService;
                }
                return v;
            }
            return 0;
            }
        }
        public decimal totalGrossService { get{
            if(summaryList != null){
                decimal v = 0;
                for(DailySummary d : summaryList){
                    v += d.GrossService;
                }
                return v;
            }
            return 0;
            }
        }
        
        public decimal totalTherapistCommission  { get{
            if(summaryList != null){
                decimal v = 0;
                for(DailySummary d : summaryList){
                    v += d.TherapistCommission ;
                }
                return v;
            }
            return 0;
            }
        }
        
        public decimal totalGrossMega   { get{
            if(summaryList != null){
                decimal v = 0;
                for(DailySummary d : summaryList){
                    v += d.Mega ;
                }
                return v;
            }
            return 0;
            }
        }
        
        public decimal totalNetMega   { get{
            if(summaryList != null){
                decimal v = 0;
                for(DailySummary d : summaryList){
                    v += d.netMega ;
                }
                return v;
            }
            return 0;
            }
        }
        
        public decimal totalMegaCommission    { get{
            if(summaryList != null){
                decimal v = 0;
                for(DailySummary d : summaryList){
                    v += d.MegaCommission ;
                }
                return v;
            }
            return 0;
            }
        }
        
        public decimal totalExpenses { get{
            if(summaryList != null){
                decimal v = 0;
                for(DailySummary d : summaryList){
                    v += d.Expenses;
                }
                return v;
            }
            return 0;
            }
        }
        
        public decimal totalSMC { get{
            if(summaryList != null){
                decimal v = 0;
                for(DailySummary d : summaryList){
                    v += d.SMC;
                }
                return v;
            }
            return 0;
            }
        }
        
        public decimal totalDiscount { get{
            if(summaryList != null){
                decimal v = 0;
                for(DailySummary d : summaryList){
                    v += d.discount;
                }
                return v;
            }
            return 0;
            }
        }
        
        public decimal totalNetSales { 
            get{
                return totalNetService + totalNetMega - totalExpenses - totalSMC; 
            }
        }
    }    
    
    public class DailySummary{
        public date SaleDate { get; set; }
        public decimal GrossService { get; set; }
        public decimal TherapistCommission { get; set; }
        public decimal NetService { 
            get{
                return GrossService - Discount - TherapistCommission;
            } 
        }
        public decimal Mega { get; set; }
        public decimal MegaCommission { get; set; }
        public decimal netMega { 
            get{
                return Mega - MegaCommission;
            } 
        }
        public decimal Expenses { get; set; }
        public decimal SMC { 
            get{
                if (managerPresent!=null)
                    if (managerPresent)
                        return .1 * TherapistCommission;
                return 0;
            }
        }
        
        public decimal NetSales { 
            get{
                return NetService + NetMega - Expenses - SMC; 
            }
        }
        public decimal discount { get; set; }
        public integer day { get; set; }
        public boolean managerPresent { get; set; }
        public Integer servicecount { get; set; }
    }
    
    public integer selectedmonth { get; set; }
    public integer selectedyear { get; set; }
    
    public List<SelectOption> getMonthOptions(){
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('0', '--Select--'));
        options.add(new SelectOption('1', 'Jan'));
        options.add(new SelectOption('2', 'Feb'));
        options.add(new SelectOption('3', 'Mar'));
        options.add(new SelectOption('4', 'Apr'));
        options.add(new SelectOption('5', 'May'));
        options.add(new SelectOption('6', 'Jun'));
        options.add(new SelectOption('7', 'Jul'));
        options.add(new SelectOption('8', 'Aug'));
        options.add(new SelectOption('9', 'Sep'));
        options.add(new SelectOption('10', 'Oct'));
        options.add(new SelectOption('11', 'Nov'));
        options.add(new SelectOption('12', 'Dec'));
        return options;
    }
    
    public List<SelectOption> getYearOptions(){
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('2017', '--Select--'));
        options.add(new SelectOption('2017', '2017'));
        options.add(new SelectOption('2016', '2016'));
        options.add(new SelectOption('2015', '2015'));
        return options;
    }
    
    public integer getMonthDays(){
        if (selectedmonth == 9 || selectedmonth==4 || selectedmonth == 6 || selectedmonth == 11)
            return 30;
        else if (selectedmonth==1 || selectedmonth==3 || selectedmonth == 5 || selectedmonth == 7 ||  selectedmonth == 8 || selectedmonth == 10 || selectedmonth == 12)
            return 31;
        return 29;      
    }
    
    
    public DailySummaryList getMonthlySummary(){
        DailySummaryList o = new DailySummaryList ();
        List<DailySummary> data = new List<DailySummary>();
        List<Client_Service__c> services = [Select Id, Date_Time__c, Client__r.First_Name__c, Client__r.Last_Name__c, service__r.service_type__c,
                        Service__r.Name__c, Service__r.Price__c, Service__r.Commission__c, Discount__c, Confirmed_By__c,
                        (Select Id, Client_Service__c, Amount__c, Product_Sale__c, Staff__r.Alias__c, Date__c from Staff_Commissions__r)
                         from Client_Service__c
                        where CALENDAR_MONTH(Date_Time__c) =: selectedmonth and CALENDAR_Year(Date_Time__c) =: selectedYear];
        
        Set<String> serviceIds = new Set<String>();
        Map<Date, List<ClientServiceController.ClientService>> dailySales = new Map<Date, List<ClientServiceController.ClientService>>();
        
        for (Client_Service__c s : services){
            serviceIds.add(s.Id);
        }
        
      
        List<Staff_Commission__c> pcommissions = [Select Id, Client_Service__c, Amount__c, 
                Product_Sale__c, Staff__r.Alias__c, Date__c from Staff_Commission__c 
                where Product_Sale__c!=null and  CALENDAR_MONTH(Date__c) =: selectedmonth and CALENDAR_Year(Date__c) =: selectedYear]; 
        
        for (Client_Service__c s : services){
            String th = '';
            decimal comm =0;
            for(Staff_Commission__c com : s.Staff_Commissions__r){
                th+= com.Staff__r.Alias__c+',';
                comm+= com.Amount__c==null? 0: com.Amount__c;
            }
            ClientServiceController.ClientService cs = BodyTechUtil.toClientService(s,  comm, th);
            if (dailySales.ContainsKey(s.Date_Time__c)){
                List<ClientServiceController.ClientService> sales = dailySales.get(s.Date_Time__c);
                sales.add(cs);
                dailySales.put(s.Date_Time__c, sales);
            }else{
                dailySales.put(s.Date_Time__c, new List<ClientServiceController.ClientService> { cs });
            }
            
            
        }  
        
        
        List<Product_Sale__c> Sales = [Select Id, 
                                              Final_Amount__c, 
                                              Discount__c, 
                                              Amount__c, 
                                              Staff__r.Id, 
                                              Staff__r.Name__c, 
                                              Product__r.Id, 
                                              Date__c,
                                              Product__r.Name__c 
                                                  from Product_Sale__c 
                                                  where CALENDAR_MONTH(Date__c) =: selectedmonth and CALENDAR_Year(Date__c) =: selectedYear
                                                  and Type__c='Sale'];      
        Map<Date, List<Product_Sale__c>> dailyMega = new Map<Date, List<Product_Sale__c>>();
        
        for(Product_Sale__c s : sales){
            if (dailyMega.ContainsKey(s.Date__c)){
                List<Product_Sale__c> mega = dailyMega.get(s.date__c);
                mega.add(s);
                dailyMega.put(s.date__c, mega);
            }else{
                dailyMega.put(s.Date__c, new List<Product_Sale__c> { s } );
            }
        }
        
        Map<Date, List<Expense__c>> dailyExpenses = new Map<Date, List<Expense__c>>();
        for(Expense__c e : [Select Id, Date__c, Amount__c from Expense__c where CALENDAR_MONTH(Date__c) =: selectedmonth and CALENDAR_Year(Date__c) =: selectedYear]){
            if (dailyExpenses.ContainsKey(e.Date__c)){
                List<Expense__c> expenses = dailyExpenses.get(e.date__c);
                expenses.add(e);
                dailyExpenses.put(e.date__c, expenses);
            }else{
                dailyExpenses.put(e.Date__c, new List<Expense__c> { e } );
            }
        }
        
        
        
        for (Integer i=0; i< getMonthDays() ; i++){
            integer x = i+1;
            decimal grossService = 0;
            decimal thComm = 0;
            decimal mega = 0;
            decimal megaComm = 0;
            decimal netService = 0;
            decimal exp = 0;
            decimal smc = 0;
            decimal netSales = 0;
            decimal disc = 0;
                        
            DailySummary s = new DailySummary();
            s.SaleDate = date.newinstance(selectedYear, selectedmonth, x);
            s.day = x;
            Integer serviceCount =0;
            for (Date d : dailySales.KeySet()){
                if (d.day() == x){
                    for(ClientServiceController.ClientService sale : dailySales.get(d)){
                        grossService += sale.amount==null ? 0 : sale.amount;       
                        thComm += sale.Commission==null ? 0 : sale.Commission;                        
                        disc += sale.discount==null ? 0 : sale.discount;
                        serviceCount ++;
                    }
                }
            }
            
            for (Date d : dailyMega.KeySet()){
                if (d.day() == x){
                    for (Product_Sale__c p : dailyMega.get(d)){
                        if (p.Amount__c != null){
                            mega += p.Amount__c;                            
                        }
                    }                   
                }
            }
            
            for(Staff_Commission__c com : pcommissions){
                        if(com.Date__c.day()==x && com.Product_Sale__c!=null)
                        {
                            if(com.Amount__c!=null)
                            megaComm+= com.Amount__c;
                        }
                    }
            
            for (Date d : dailyExpenses.KeySet()){
                if (d.day() == x){
                    for (Expense__c e : dailyExpenses.get(d)){
                        if (e.Amount__c != null)
                            exp+= e.Amount__c;
                    }
                }
            }
            
            s.discount = disc;
            s.therapistcommission = thcomm;
            s.grossservice = grossservice;
            s.mega = mega;
            s.megacommission = megacomm;
            s.servicecount = serviceCount;
            //s.smc = smc;
            s.expenses = exp;
            data.add(s);
        }
        o.summaryList = data;
        return o;
    }
    
    
}