src/objects/Email__c.object
<CustomObject>
    <description>Object used by workflow to send out email messages.</description>
    <fields>
        <fullName>Exam_Name__c</fullName>
        <label>Exam Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <description>Used to store link to the exam.</description>
        <label>Link</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Recipient_Name__c</fullName>
        <description>Used to store the name of the recipient. This custom field is only used for the following email workflows: alert_on_new_exam and alert_on_new_top_score</description>
        <label>Recipient Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <description>Used to store the recipient&apos;s email address.</description>
        <label>Recipient</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Name__c</fullName>
        <label>Sender Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <label>Template</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Email</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Examination__c.object
<CustomObject>
    <description>Details of the Exams</description>
    <fields>
        <fullName>Name__c</fullName>
        <description>Examination Name</description>
        <label>Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Passing_Rate__c</fullName>
        <description>Passing rate for the exam.</description>
        <label>Passing_Rate</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Promotion_Text__c</fullName>
        <description>Lists related Salesforce.com URLs.</description>
        <label>Promotion_Text</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Examination</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Examination_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Examinations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_Examination__c.object
<CustomObject>
    <description>Stores exams a particular user has taken. It also tracks questions not yet answered by a user (if an exam is not completed).</description>
    <fields>
        <fullName>Examination_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Examination</label>
        <referenceTo>Examination__c</referenceTo>
        <relationshipLabel>User Examinations</relationshipLabel>
        <relationshipName>User_Examinations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Perfect_Score__c</fullName>
        <label>Perfect_Score</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Profile</label>
        <referenceTo>UserProfile__c</referenceTo>
        <relationshipLabel>User Examinations</relationshipLabel>
        <relationshipName>User_Examinations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Examination</label>
    <nameField>
        <displayFormat>UE-{00000}</displayFormat>
        <label>User_Examination_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Examinations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UserProfile__c.object
<CustomObject>
    <description>Object for the user profile</description>
    <fields>
        <fullName>EmailResults__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Emails the results after taking an exam</description>
        <inlineHelpText>Emails the results after taking an exam</inlineHelpText>
        <label>Email test results</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email_Result_after_Exam__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email Result after Exam</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email of the user</description>
        <externalId>true</externalId>
        <inlineHelpText>Email of the user</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>First name</description>
        <inlineHelpText>First name</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>Last name of the user</description>
        <inlineHelpText>Last name of the user</inlineHelpText>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>User Profile</label>
    <nameField>
        <displayFormat>U-{000000}</displayFormat>
        <label>User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MAD_test.cls
public class MAD_test {
    public boolean displayInvite {get;set;}
    public UserProfile__c Send{get;set;}
    public Email__c Email{get;set;}
    public User_Examination__c User{get;set;}
    private static final String ATHENA = ' http://athena-developer-edition.ap1.force.com/';  
//    public String[] emails = new String[]{};
//    public String[] names = new String[]{};
    
    public String emailAddress1 {get; set;}
    public String friendName1 {get; set;}
    public String emailAddress2 {get; set;}
    public String friendName2 {get; set;}
    public String emailAddress3 {get; set;}
    public String friendName3 {get; set;}
    public String emailAddress4 {get; set;}
    public String friendName4 {get; set;}
    public String emailAddress5 {get; set;}
    public String friendName5 {get; set;}                
    public User_Examination__c Uexam {get; set;}  

    public void onInit()
    {
        Uexam = [Select u.Score__c, 
                 u.User_ID__c, 
                 u.User_ID__r.FirstName__c,
                 u.User_ID__r.LastName__c,
                 u.User_ID__r.Email__c,
                 u.User_ID__r.Email_Result_after_Exam__c,
                 u.Perfect_Score__c,
                 u.Examination_ID__r.Promotion_Text__c,
                 u.Examination_ID__r.Passing_Rate__c,
                 u.Examination_ID__r.Name__c 
                 from User_Examination__c u 
                 where u.ID= :ApexPages.currentPage().getParameters().get('userExamID')];
                 
           string score = '' + Uexam.Score__c;
           double ave;
           ave = ((Uexam.Score__c /Uexam.Perfect_Score__c)*100);
           
           if (Uexam.User_ID__r.Email_Result_after_Exam__c = true)
           {
                   System.debug('Email results? ' + Uexam.User_ID__r.Email_Result_after_Exam__c);
                   Email__c inform = new Email__c();
                   inform.Link__c = ATHENA;
                   inform.Result__c = score;
                   if(Uexam.Examination_ID__r.Name__c == null || Uexam.Examination_ID__r.Name__c == '')
                   {
                       inform.Exam_Name__c = 'Challenge';
                   }
                   else
                   {
                       inform.Exam_Name__c = Uexam.Examination_ID__r.Name__c;
                   }
                   inform.Recipient__c = Uexam.User_ID__r.Email__c;
                   inform.Recipient_Name__c = Uexam.User_ID__r.FirstName__c;
                    System.debug('Uexam.User_ID__r.Email__c: ' + Uexam.User_ID__r.Email__c);
                    System.debug('Recipient__c: ' + inform.Recipient__c);
                   inform.Sender_Name__c = 'Team ATHENA';
                       if (ave > Uexam.Examination_ID__r.Passing_Rate__c)
                       {
                           inform.Template__c = 'SEND_PASSED';
                       }else{
                           inform.Template__c = 'SEND_FAILED';
                       }
                   INSERT inform;
                   System.debug('inform: ' + inform);
            }   
    }


    /*    User_Examination = [Select u.User_ID__c, u.User_ID__r.FirstName__c from User_Examination__c u];
          Send = [Select u.EmailResults__c from UserProfile__c u];
    */
    public void send() 
    {
        send1();
        send2();
        send3();
        displayInvite = false;
    }
    
    public void send1()
    {
        try{
        if((friendName1 != null && Email.Recipient__c != null))
        {
            Email__c dataToInsert = new Email__c();
            dataToInsert.Recipient_Name__c = friendName1;
            //dataToInsert.Recipient__c = emailAddress1;
            dataToInsert.Link__c = ATHENA;
            dataToInsert.Exam_Name__c = Uexam.Examination_ID__r.Name__c;
            dataToInsert.Sender_Name__c = Uexam.User_ID__r.FirstName__c;
            dataToInsert.Template__c = 'INVITE';
            INSERT dataToInsert;
            friendName1 = '';
            emailAddress1 = '';
        } 
        }catch(Exception ex)
        {
            ApexPages.addMessages(ex);
        }
    } 
    
    public void send2()
    {
        if((friendName2 != null && Email.Recipient__c != null))
        {
            Email__c dataToInsert = new Email__c();
            dataToInsert.Recipient_Name__c = friendName2;
            //dataToInsert.Recipient__c = emailAddress2;
            dataToInsert.Link__c = ATHENA;
            dataToInsert.Exam_Name__c = Uexam.Examination_ID__r.Name__c;
            dataToInsert.Sender_Name__c = Uexam.User_ID__r.FirstName__c;
            dataToInsert.Template__c = 'INVITE';
            INSERT dataToInsert;
            friendName2 = '';
            emailAddress2 = ''; 
        }
    } 
    
    public void send3()
    {
        if((friendName3 != null && Email.Recipient__c != null))
        {
            Email__c dataToInsert = new Email__c();
            dataToInsert.Recipient_Name__c = friendName3;
            //dataToInsert.Recipient__c = emailAddress3;
            dataToInsert.Link__c = ATHENA;
            dataToInsert.Exam_Name__c = Uexam.Examination_ID__r.Name__c;
            dataToInsert.Sender_Name__c = Uexam.User_ID__r.FirstName__c;
            dataToInsert.Template__c = 'INVITE';
            INSERT dataToInsert;
            friendName3 = '';
            emailAddress3 = ''; 
        }else{
        
        }
    } 
/*    
    public void send4()
    {
        if((friendName1 != null && emailAddress1 != null) || (friendName1 != '' && emailAddress1 !='' ))
        {
            Email__c dataToInsert = new Email__c();
            dataToInsert.Recipient_Name__c = friendName4;
            //dataToInsert.Recipient__c = emailAddress4;
            dataToInsert.Link__c = ATHENA;
            dataToInsert.Exam_Name__c = Uexam.Examination_ID__r.Name__c;
            dataToInsert.Sender_Name__c = Uexam.User_ID__r.FirstName__c;
            dataToInsert.Template__c = 'INVITE';
            INSERT dataToInsert;
            friendName4 = '';
            emailAddress4 = ''; 
        }
    } 
    
    public void send5()
    {
        if((friendName1 != null && emailAddress1 != null) || (friendName1 != '' && emailAddress1 !='' ))
        {
            Email__c dataToInsert = new Email__c();
            dataToInsert.Recipient_Name__c = friendName5;
            //dataToInsert.Recipient__c = emailAddress5;
            dataToInsert.Link__c = ATHENA;
            dataToInsert.Exam_Name__c = Uexam.Examination_ID__r.Name__c;
            dataToInsert.Sender_Name__c = Uexam.User_ID__r.FirstName__c;
            dataToInsert.Template__c = 'INVITE';
            INSERT dataToInsert;
            friendName5 = '';
            emailAddress5 = ''; 
        }
    } 
*/
/*        
        if((friendName1 != null && emailAddress1 != null) || (friendName1 != '' && emailAddress1 !='' ))
        {
            Email__c dataToInsert = new Email__c();
            dataToInsert.Recipient_Name__c = friendName1;
            dataToInsert.Recipient__c = emailAddress1;
            dataToInsert.Link__c = ATHENA;
            dataToInsert.Exam_Name__c = Uexam.Examination_ID__r.Name__c;
            dataToInsert.Sender_Name__c = Uexam.User_ID__r.FirstName__c;
            dataToInsert.Template__c = 'INVITE';
            INSERT dataToInsert;
            friendName1 = '';
            emailAddress1 = '';   
        }

        if(friendName2 != null && emailAddress2 != null)
        {
            Email__c dataToInsert2 = new Email__c();
            dataToInsert2.Recipient_Name__c = friendName2;
            //dataToInsert2.Recipient__c = emailAddress2;
            dataToInsert2.Link__c = ATHENA;
            dataToInsert2.Exam_Name__c = Uexam.Examination_ID__r.Name__c;
            dataToInsert2.Sender_Name__c = Uexam.User_ID__r.FirstName__c;
            dataToInsert2.Template__c = 'INVITE';
            //INSERT dataToInsert2;
            friendName2 = '';
            emailAddress2 = '';
        }

        if(friendName3 != null && emailAddress3 != null)
        {
            Email__c dataToInsert3 = new Email__c();
            dataToInsert3.Recipient_Name__c = friendName3;
            //dataToInsert3.Recipient__c = emailAddress3;
            dataToInsert3.Link__c = ATHENA;
            dataToInsert3.Exam_Name__c = Uexam.Examination_ID__r.Name__c;
            dataToInsert3.Sender_Name__c = Uexam.User_ID__r.FirstName__c;
            dataToInsert3.Template__c = 'INVITE';
            //INSERT dataToInsert3;
            friendName3 = '';
            emailAddress3 = '';
        }    

        if(friendName4 != null && emailAddress4 != null)
        {
            Email__c dataToInsert4 = new Email__c();
            dataToInsert4.Recipient_Name__c = friendName4;
            dataToInsert4.Recipient__c = emailAddress4;
            dataToInsert4.Link__c = ATHENA;
            dataToInsert4.Exam_Name__c = Uexam.Examination_ID__r.Name__c;
            dataToInsert4.Sender_Name__c = Uexam.User_ID__r.FirstName__c;
            dataToInsert4.Template__c = 'INVITE';
           // INSERT dataToInsert4;
            friendName4 = '';
            emailAddress4 = '';
        }    

        if((friendName5 != null & emailAddress5 != null) | (friendName5 != '' & emailAddress5 != ''))
        {
        try{
            Email__c dataToInsert5 = new Email__c();
            dataToInsert5.Recipient_Name__c = friendName5;
            dataToInsert5.Recipient__c = emailAddress5;
            dataToInsert5.Link__c = ATHENA;
            dataToInsert5.Exam_Name__c = Uexam.Examination_ID__r.Name__c;
            dataToInsert5.Sender_Name__c = Uexam.User_ID__r.FirstName__c;
            dataToInsert5.Template__c = 'INVITE';
            INSERT dataToInsert5;
            friendName5 = '';
            emailAddress5 = '';
            }Catch(DMLException ex){        
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'yoh');
            ApexPages.addMessage(myMsg);}

        }                  
    }*/
    
    public void invite() {
        displayInvite = true;
    }
    
    public void cancel(){
        friendName1 = ''; friendName2 = ''; friendName3 = ''; friendName4 = ''; friendName5 = '';
        emailAddress1 = ''; emailAddress2 = ''; emailAddress3 = ''; emailAddress4 = ''; emailAddress5 = '';
        displayInvite = false;
    }    
}