src/objects/Email__c.object
<CustomObject>
    <description>Object used by workflow to send out email messages.</description>
    <label>Email</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Examination__c.object
<CustomObject>
    <description>Details of the Exams</description>
    <fields>
        <fullName>Badge__c</fullName>
        <description>Stores link where the image is located.</description>
        <label>Badge</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Examination Name</description>
        <label>Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Examination</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Examination_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Examinations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_Examination__c.object
<CustomObject>
    <description>Stores exams a particular user has taken. It also tracks questions not yet answered by a user (if an exam is not completed).</description>
    <fields>
        <fullName>Date_Completed__c</fullName>
        <label>Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Created__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>Date when the exam was created for a specific user</description>
        <label>Date_Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Earned_Badge__c</fullName>
        <description>Used to compare user&apos;s score with achievement rate.</description>
        <formula>IF((( Score__c / Perfect_Score__c ) &gt;  Examination_ID__r.Achievement_Rate__c) ,&apos;True&apos;, &apos;False&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Earned_Badge</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Examination_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Examination</label>
        <referenceTo>Examination__c</referenceTo>
        <relationshipLabel>User Examinations</relationshipLabel>
        <relationshipName>User_Examinations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ongoing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <description>Used to validate user exam session.</description>
        <label>Token</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>User_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Profile</label>
        <referenceTo>UserProfile__c</referenceTo>
        <relationshipLabel>User Examinations</relationshipLabel>
        <relationshipName>User_Examinations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Examination</label>
    <nameField>
        <displayFormat>UE-{00000}</displayFormat>
        <label>User_Examination_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Examinations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UserProfile__c.object
<CustomObject>
    <description>Object for the user profile</description>
    <fields>
        <fullName>Date_Activated__c</fullName>
        <description>Date when the account was activated</description>
        <label>Date Activated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EmailNewExam__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Sends an email if there is a new exam added</description>
        <inlineHelpText>Sends an email if there is a new exam added</inlineHelpText>
        <label>Email on new exam</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EmailResults__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Emails the results after taking an exam</description>
        <inlineHelpText>Emails the results after taking an exam</inlineHelpText>
        <label>Email test results</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email of the user</description>
        <externalId>true</externalId>
        <inlineHelpText>Email of the user</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>First name</description>
        <inlineHelpText>First name</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>Last name of the user</description>
        <inlineHelpText>Last name of the user</inlineHelpText>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Country of origin</description>
        <inlineHelpText>Country of origin</inlineHelpText>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Ascension Island</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <description>Token used for authentication.</description>
        <label>Token</label>
        <type>TextArea</type>
    </fields>
    <label>User Profile</label>
    <nameField>
        <displayFormat>U-{000000}</displayFormat>
        <label>User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProfileController.cls
/*
Made by Joey: 
Controller for editing or viewing of the user's profile.
It includes the viewing of the badges and the facility to resume exams.
It also activates the user account if incase it hasn't been activated yet
*/

public class ProfileController {
    public ID  userID{get; set;} 
    private String token;
    private String oldEmail;
    public Boolean editMode{get; set;}
    public UserProfile__c userProfile {get; set;}  
    
    public PageReference checkParameters()
    {
        if (userID== null)       
            return Page.Exception;        
        else
        {
            if (editMode)
                activateUserProfile();
            return null;        
        }    
    }    
    public ProfileController()
    {
        userID = ApexPages.currentPage().getParameters().get('id');
        token = ApexPages.currentPage().getParameters().get('token');
        editMode = false;
        /** Validate token*/
        if (token != null )
        {
            Integer temp = [SELECT count() FROM UserProfile__c WHERE ID = :userID AND Token__c = :token];
            if ( temp > 0)
                editMode = true;
            else
                editMode = false;                
        }
        if (userID != null)
        {
            userProfile = [Select Date_Activated__c, Email__c, EmailNewExam__c, EmailResults__c, FirstName__c, Id, LastName__c, Location__c from UserProfile__c 
                                WHERE ID=:userID] ;    
        }        
        else
            userProfile = new UserProfile__c();
    }
    public void activateUserProfile()
    {
        if (userProfile.Date_Activated__c == null)
        {
            userProfile.Date_Activated__c = DateTime.Now();
            update(userProfile); 
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO,'Account activated successfully. You may now take exams in the Test Center.');
            ApexPages.addMessage(myMsg);               
            
        }        
    }
    public User_Examination__c[] getBadges()
    {   
        //Condition for a badge. The user should be able to reach the achievement rate first time around.
        User_Examination__c[] completedExams = [Select u.Date_Completed__c, u.Earned_Badge__c, u.Examination_ID__c,u.Examination_ID__r.Badge__c, u.Examination_ID__r.Name__c, u.Score__c, u.Status__c, u.User_ID__c, u.User_ID__r.Id from User_Examination__c u WHERE u.User_ID__r.Id = :userID And u.Status__c = 'Completed' ORDER BY u.Date_Created__c ASC];
        
        Map<string, User_Examination__c> userExamMap = new Map<String, User_Examination__c>();
        
        for(User_Examination__c userExam : completedExams ){
           if (!userExamMap.containsKey(userExam.Examination_ID__c))
               userExamMap.put(userExam.Examination_ID__c, userExam);
        }
        User_Examination__c[] firstExams = userExamMap.values();

        List<User_Examination__c> theExams =  new List<User_Examination__c>();
        for(User_Examination__c userExam : firstExams ){     
           if (userExam.Earned_Badge__c == 'True' )
                theExams.add(userExam);                   
        }

         
        return theExams;
    }
    public User_Examination__c[] getIncompleteExams()
    {        
        return  [Select u.Token__c, u.Examination_ID__c,u.ID, u.Examination_ID__r.Name__c, u.Status__c, u.User_ID__c, u.User_ID__r.Id from User_Examination__c u WHERE u.User_ID__r.Id = :userID And u.Status__c = 'Ongoing'];
    }
    public PageReference save() {
        try 
        {
            upsert(userProfile);            
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO,'Profile updated successfully.');
            ApexPages.addMessage(myMsg);                   
        } 
        catch(System.DMLException e) 
        {
            ApexPages.addMessages(e);
            return null;
        }
        return null;       
    }
    
    static testMethod void profileControllerTest() {
        /* Instantiate the current page*/
        PageReference profilePage = Page.Profile;
        Test.setCurrentPage(profilePage);       
        
        ProfileController profileController = new ProfileController();      
        profileController.checkParameters().getUrl();
        Test.setCurrentPage(profilePage);
        
        UserProfile__c testProfile = [Select Id, Token__c From UserProfile__c Limit 1];
        
        ApexPages.currentPage().getParameters().put('id', testProfile.Id);
        profileController = new ProfileController();
        
        ApexPages.currentPage().getParameters().put('token', testProfile.Token__c);     
        
        /* Editable Profile*/
        profileController = new ProfileController();
        profileController.editMode = true;
        profileController.activateUserProfile();
        profileController.checkParameters();
        profileController.getBadges();
        profileController.getIncompleteExams();             
        profileController.save();
        
        /* Viewing profile */
        profileController = new ProfileController();
        profileController.editMode = false;     
        profileController.getBadges();
        profileController.getIncompleteExams();             
        profileController.save();
    }
    
}