src/objects/Email__c.object
<CustomObject>
    <description>Object used by workflow to send out email messages.</description>
    <fields>
        <fullName>Link__c</fullName>
        <description>Used to store link to the exam.</description>
        <label>Link</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Recipient_Name__c</fullName>
        <description>Used to store the name of the recipient. This custom field is only used for the following email workflows: alert_on_new_exam and alert_on_new_top_score</description>
        <label>Recipient Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <description>Used to store the recipient&apos;s email address.</description>
        <label>Recipient</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sender_Name__c</fullName>
        <label>Sender Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender__c</fullName>
        <description>Used to store the sender&apos;s email address</description>
        <label>Sender</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <label>Template</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Email</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UserProfile__c.object
<CustomObject>
    <description>Object for the user profile</description>
    <fields>
        <fullName>Date_Activated__c</fullName>
        <description>Date when the account was activated</description>
        <label>Date Activated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email of the user</description>
        <externalId>true</externalId>
        <inlineHelpText>Email of the user</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>First name</description>
        <inlineHelpText>First name</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>Last name of the user</description>
        <inlineHelpText>Last name of the user</inlineHelpText>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Country of origin</description>
        <inlineHelpText>Country of origin</inlineHelpText>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Ascension Island</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Philippines</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <description>Token used for authentication.</description>
        <label>Token</label>
        <type>TextArea</type>
    </fields>
    <label>User Profile</label>
    <nameField>
        <displayFormat>U-{000000}</displayFormat>
        <label>User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NewProfileController.cls
public class NewProfileController {
    private static final String ATHENA_URL = ' http://athena-developer-edition.ap1.force.com/';
    public UserProfile__c userProfile{get; set;}  
    
    public String userEmail{get; set;}
    public Boolean activationLink{get; set;}
      
    public NewProfileController () {
          userProfile = new UserProfile__c();
    }
    
    /** Checks if the email already exists */
    private Boolean emailExists(String email)
    {
        Integer count = [SELECT count() from UserProfile__c WHERE Email__c = :email];
        if (count == 0)
            return false;
        else
            return true;    
    }
    /* Sends the Profile link to the email */
    public PageReference sendProfile()
    {
        UserProfile__c a = new UserProfile__c(Email__c = userEmail);
   
        Pattern MyPattern = Pattern.compile('^\\w+[\\w-\\.]*\\@\\w+((-\\w+)|(\\w*))\\.[a-z]{2,3}$'); /*Validate email using regex*/
        Matcher MyMatcher = MyPattern.matcher(userEmail); 
        
        Boolean hasMatch = MyMatcher.matches();
        if (hasMatch)
        {
            if (emailExists(userEmail))
            {
                emailProfileLink(userEmail);
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO,'Please check your email for the profile link.');
                ApexPages.addMessage(myMsg);
                userProfile.clear();
                return null;          
            }
            else
            {
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Email does not exist in the database. Please register first.');
                ApexPages.addMessage(myMsg);            
            }
        }
        else
        {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Please input a valid email address.');
            ApexPages.addMessage(myMsg);            
        }
        return null;
    
    }
    public void emailProfileLink(String email)
    {
        UserProfile__c theProfile = [SELECT ID,FirstName__c,   Token__c FROM UserProfile__c WHERE Email__c = :email];
        
        String theURL = ATHENA_URL + 'Profile?id=' + theProfile.ID + '&Token=' + theProfile.Token__c;
        Email__c theEmail = new Email__c();
        theEmail.Template__c = 'SEND_PROFILE_LINK';
        theEmail.Sender__c = 'psodchallenge@gmail.com';
        theEmail.Sender_Name__c = 'Athena';
        theEmail.Recipient__c = email;
        //theEmail.Recipient__c = 'psodchallenge@gmail.com';  //TODO - CHange to email
        theEmail.Recipient_Name__c = theProfile.FirstName__c;
        theEmail.Link__c = theURL;
        
        insert theEmail;

    }
    public PageReference emailActivationLink() {
        emailProfileLink(userProfile.Email__c);  
        activationLink = false;
        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO,'Activation link sent.');
        ApexPages.addMessage(myMsg); 
        return null;
        
    }
    public PageReference register() {
        if (userProfile.Location__c == 'Select Location'  | userProfile.Location__c == null)
        {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Please select a location');
            ApexPages.addMessage(myMsg);
            return null;
        
        }
        //Checks if the email already exists in the database
        if (!emailExists(userProfile.Email__c))
        {        
            insert userProfile;        
            emailProfileLink(userProfile.Email__c);
            userProfile = new UserProfile__c();
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO,'Thank you for registering. Please check your email for the profile link.');
            ApexPages.addMessage(myMsg);
            userEmail = ''; /* Clear the userEmail */        
            return null;
        }
        else 
        {
            UserProfile__c uProfile = [SELECT ID, Date_Activated__c from UserProfile__c WHERE Email__c = :userProfile.Email__c];
            if (uProfile.Date_Activated__c == null)
            {
                activationLink = true; 
                return null;                                   
            }
            else
            {
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Email already exists. Please register using a different email.');
                ApexPages.addMessage(myMsg);
            }
        }
        //Todo Email user that he/she can now view his/her profile through his/her email
        return null;
    }
    static testMethod void newProfileControllerTest() {
        PageReference newProfilePage = Page.NewProfile;
        Test.setCurrentPage(newProfilePage);  
        
        UserProfile__c existingProfile = [Select Email__c from UserProfile__c Limit 1];
        NewProfileController newProfileController = new NewProfileController();
        newProfileController.userEmail = 'no@email.com';
        newProfileController.sendProfile();
        newProfileController.userEmail = '';
        newProfileController.sendProfile();
        newProfileController.userEmail = existingProfile.Email__c;
        newProfileController.sendProfile();
            
        newProfileController.userProfile.Location__c  = 'Select Location';      
        newProfileController.register();
        
        newProfileController.userProfile.FirstName__c = 'Joey';
        newProfileController.userProfile.LastName__c  = 'Chan';
        newProfileController.userProfile.Email__c     = existingProfile.Email__c;
        newProfileController.userProfile.Location__c  = 'Philippines';
        
        newProfileController.register();
        
        newProfileController.userProfile.FirstName__c = 'Joey';
        newProfileController.userProfile.LastName__c  = 'Chan';
        newProfileController.userProfile.Email__c     = 'test@myemail.com';
        newProfileController.userProfile.Location__c  = 'Philippines';
        newProfileController.register();
        
    }
}