src/objects/Email__c.object
<CustomObject>
    <description>Object used by workflow to send out email messages.</description>
    <label>Email</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Examination__c.object
<CustomObject>
    <description>Details of the Exams</description>
    <fields>
        <fullName>Name__c</fullName>
        <description>Examination Name</description>
        <label>Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Passing_Rate__c</fullName>
        <description>Passing rate for the exam.</description>
        <label>Passing_Rate</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Examination</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Examination_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Examinations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_Examination__c.object
<CustomObject>
    <description>Stores exams a particular user has taken. It also tracks questions not yet answered by a user (if an exam is not completed).</description>
    <fields>
        <fullName>Date_Created__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>Date when the exam was created for a specific user</description>
        <label>Date_Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ongoing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Profile</label>
        <referenceTo>UserProfile__c</referenceTo>
        <relationshipLabel>User Examinations</relationshipLabel>
        <relationshipName>User_Examinations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Examination</label>
    <nameField>
        <displayFormat>UE-{00000}</displayFormat>
        <label>User_Examination_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Examinations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UserProfile__c.object
<CustomObject>
    <description>Object for the user profile</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email of the user</description>
        <externalId>true</externalId>
        <inlineHelpText>Email of the user</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>First name</description>
        <inlineHelpText>First name</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>Last name of the user</description>
        <inlineHelpText>Last name of the user</inlineHelpText>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Country of origin</description>
        <inlineHelpText>Country of origin</inlineHelpText>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Ascension Island</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Philippines</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Profile</label>
    <nameField>
        <displayFormat>U-{000000}</displayFormat>
        <label>User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TriggerTests.cls
@isTest

/*
	Test Methods created by Joey and Kringle

*/
private class TriggerTests
{   
    static testMethod void newExamTriggerTest() 
    {
        test.startTest();  
        
        // Create and insert new Examination
        Examination__c examination = new Examination__c 
        (
            Name__c='Adobe Flex',
            Passing_Rate__c=70
        );
            
        insert examination;
        
        test.stopTest();
    }
    static testMethod void userExamTokenTriggerTest() 
    {
        test.startTest();  
        
        UserProfile__c uProf = [Select Id from UserProfile__c Limit 1];
        User_Examination__c uExam = new User_Examination__c();
        uExam.User_ID__c = uProf.Id;        
        uExam.Date_Created__c = System.now();
        uExam.Status__c = 'New';                    
        insert uExam;
        
        test.stopTest();
    }
    static testMethod void userProfileTokenTriggerTest() 
    {
        test.startTest();  
        
        UserProfile__c uProf = new UserProfile__c();
        uProf.FirstName__c = 'John';
        uProf.LastName__c = 'Doe';
        uProf.Email__c = 'Email@me.com';
        uProf.Location__c = 'Philippines';
        
        insert uProf;
        
        test.stopTest();
    }          
}