src/objects/Email__c.object
<CustomObject>
    <description>Object used by workflow to send out email messages.</description>
    <fields>
        <fullName>Link__c</fullName>
        <description>Used to store link to the exam.</description>
        <label>Link</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Recipient_Name__c</fullName>
        <description>Used to store the name of the recipient. This custom field is only used for the following email workflows: alert_on_new_exam and alert_on_new_top_score</description>
        <label>Recipient Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <description>Used to store the recipient&apos;s email address.</description>
        <label>Recipient</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sender_Name__c</fullName>
        <label>Sender Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender__c</fullName>
        <description>Used to store the sender&apos;s email address</description>
        <label>Sender</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <label>Template</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Email</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Examination__c.object
<CustomObject>
    <description>Details of the Exams</description>
    <fields>
        <fullName>Date_Added__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>Date when the exam was created.</description>
        <label>Date Added</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Description1__c</fullName>
        <label>Description1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Description2__c</fullName>
        <label>Description2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Examination Name</description>
        <label>Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Examination</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Examination_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Examinations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_Examination__c.object
<CustomObject>
    <description>Stores exams a particular user has taken. It also tracks questions not yet answered by a user (if an exam is not completed).</description>
    <fields>
        <fullName>Examination_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Examination</label>
        <referenceTo>Examination__c</referenceTo>
        <relationshipLabel>User Examinations</relationshipLabel>
        <relationshipName>User_Examinations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ongoing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <description>Used to validate user exam session.</description>
        <label>Token</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>User_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Profile</label>
        <referenceTo>UserProfile__c</referenceTo>
        <relationshipLabel>User Examinations</relationshipLabel>
        <relationshipName>User_Examinations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Examination</label>
    <nameField>
        <displayFormat>UE-{00000}</displayFormat>
        <label>User_Examination_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Examinations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UserProfile__c.object
<CustomObject>
    <description>Object for the user profile</description>
    <fields>
        <fullName>Date_Activated__c</fullName>
        <description>Date when the account was activated</description>
        <label>Date Activated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email of the user</description>
        <externalId>true</externalId>
        <inlineHelpText>Email of the user</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>First name</description>
        <inlineHelpText>First name</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <description>Token used for authentication.</description>
        <label>Token</label>
        <type>TextArea</type>
    </fields>
    <label>User Profile</label>
    <nameField>
        <displayFormat>U-{000000}</displayFormat>
        <label>User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/examListController.cls
public class examListController 
{
    private static final String ATHENA_URL = ' http://athena-developer-edition.ap1.force.com/';
    public List<Examination__c> SearchExams = new List<Examination__c>();
    public String examName {get; set;}
    public String email {get; set;}
    public Boolean isSearchResult {get; set;}
    public String TabInFocus {get; set;}

    public examListController()
    {
        SearchExams = [SELECT e.Name__c, e.Date_Added__c, e.Description1__c from Examination__c e ORDER BY e.Name__c];
        isSearchResult = false;
    }
   
    public PageReference searchExamsAction()
    { 
        examName = examName.trim();
        if(examName == '')
        {
            SearchExams = [SELECT e.Name__c, e.Date_Added__c, e.Description1__c from Examination__c e ORDER BY e.Name__c];
        }
        else
        {
            SearchExams = [SELECT e.Name__c, e.Date_Added__c, e.Description1__c from Examination__c e WHERE (e.Name__c LIKE :'%' + examName + 
                '%' OR e.Description1__c LIKE :'%' + examName + '%' OR e.Description2__c LIKE :'%' + examName + '%') ORDER BY e.Name__c];
               
            if(SearchExams.isEmpty() || SearchExams == null)
            {
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO,'Sorry, no records were found for ' + examName + '.');
                ApexPages.addMessage(myMsg);
            }
            
        }
        isSearchResult = true;
        return null;   
    }  
    
    public PageReference viewAllExamsAction()
    {   
        examName = '';
        SearchExams = [SELECT e.Name__c, e.Date_Added__c, e.Description1__c from Examination__c e ORDER BY e.Name__c];

        isSearchResult = false;
        return null;    
    }      
   
    public List<Examination__c> getSearchExams()
    {
        return SearchExams;
    }
   
    public Boolean isExistingEmail(String email)
    {
        Integer count = [SELECT count() from UserProfile__c WHERE Email__c = :email];
        if (count == 0)
        {
            return false;
        }
        else
        {
            return true;
        }
    }
    
    public PageReference sendEmailAction()
    {
        Pattern MyPattern = Pattern.compile('^\\w+[\\w-\\.]*\\@\\w+((-\\w+)|(\\w*))\\.[a-z]{2,3}$');
        Matcher MyMatcher = MyPattern.matcher(email); 
        Boolean hasMatch = MyMatcher.matches();
        
        if(hasMatch)
        {
            if(isExistingEmail(email))
            {
                UserProfile__c userProfile = [SELECT Id, FirstName__c, Date_Activated__c FROM UserProfile__c WHERE Email__c = :email];
                
                if (userProfile.Date_Activated__c == null)
                {
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'An activation link has been sent to your email. Please activate your account first before taking an exam.');
                    ApexPages.addMessage(myMsg);              
                }
                else
                {            
                    User_Examination__c userExamToInsert = new User_Examination__c();
                    userExamToInsert.User_ID__c = userProfile.Id;
                    userExamToInsert.Status__c = 'New';
                    INSERT userExamToInsert;
                    
                    User_Examination__c userExam = [SELECT Id, Token__c FROM User_Examination__c WHERE User_ID__c = :userProfile.Id AND Status__c = 'New' AND Examination_ID__c = null LIMIT 1];
                    String theURL = ATHENA_URL +'TakeChallenge?userExamID='+ userExam.ID + '&token='+userExam.Token__c; 
                    
                    Email__c theEmail = new Email__c();
                    theEmail.Template__c = 'CHALLENGE';
                    theEmail.Sender__c = 'psodchallenge@gmail.com';
                    theEmail.Sender_Name__c = 'Team ATHENA';
                    theEmail.Recipient__c = email;
                    theEmail.Recipient_Name__c = userProfile.FirstName__c;
                    theEmail.Link__c = theURL;
                    INSERT theEmail;
                    
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO,'Please check your email for the Challenge link.');
                    ApexPages.addMessage(myMsg); 
                }
            }  
            else
            {
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Email not found in the system. Please create a new profile in the Profile page.');
                ApexPages.addMessage(myMsg);            
            } 
        }
        else
        {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Please input a valid email address.');
            ApexPages.addMessage(myMsg);           
        }
             
        return null;
    }         
    
 
}