src/objects/Email__c.object
<CustomObject>
    <description>Object used by workflow to send out email messages.</description>
    <label>Email</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Examination__c.object
<CustomObject>
    <description>Details of the Exams</description>
    <fields>
        <fullName>Date_Added__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>Date when the exam was created.</description>
        <label>Date Added</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Description1__c</fullName>
        <label>Description1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Examination Name</description>
        <label>Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Passing_Rate__c</fullName>
        <description>Passing rate for the exam.</description>
        <label>Passing_Rate</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Examination</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Examination_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Examinations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UserProfile__c.object
<CustomObject>
    <description>Object for the user profile</description>
    <fields>
        <fullName>Date_Activated__c</fullName>
        <description>Date when the account was activated</description>
        <label>Date Activated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email of the user</description>
        <externalId>true</externalId>
        <inlineHelpText>Email of the user</inlineHelpText>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>First name</description>
        <inlineHelpText>First name</inlineHelpText>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>Last name of the user</description>
        <inlineHelpText>Last name of the user</inlineHelpText>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Country of origin</description>
        <inlineHelpText>Country of origin</inlineHelpText>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Ascension Island</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Philippines</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Profile</label>
    <nameField>
        <displayFormat>U-{000000}</displayFormat>
        <label>User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestExamListController.cls
@isTest
private class TestExamListController
{   
    static testMethod void myUnitTest() 
    {
        test.startTest();  
        
        Examination__c examination = new Examination__c 
        (
            Name__c='Adobe Flex',
            Date_Added__c=Datetime.now(),
            Description1__c='This is a sample exam',
            Passing_Rate__c=70
        );
        insert examination;
        
        examListController con = new examListController();
        
        con.viewAllExamsAction();
        con.getSearchExams();
        
        con.examName = '';
        con.searchExamsAction();        
        
        Examination__c examinationObj = [SELECT Name__c FROM Examination__c WHERE Name__c='Adobe Flex' LIMIT 1];
        con.examName = examinationObj.Name__c;
        con.searchExamsAction();
        
        UserProfile__c userProfile = new UserProfile__c
        (
            FirstName__c='Kringle',
            LastName__c='Atanacio',
            Location__c='Philippines',
            Email__c='test@yahoo.com',
            Date_Activated__c=Datetime.now()
        );
        insert userProfile;
        
        UserProfile__c userProfileObj = [SELECT Email__c FROM UserProfile__c WHERE Email__c='test@yahoo.com' LIMIT 1];
        con.email = userProfileObj.Email__c;
        con.sendEmailAction();
        
        UserProfile__c userProfile2 = new UserProfile__c
        (
            FirstName__c='Katrina',
            LastName__c='Atanacio',
            Location__c='Afghanistan',
            Email__c='test2@yahoo.com'
        );
        insert userProfile2;
        
        UserProfile__c userProfileObj2 = [SELECT Email__c FROM UserProfile__c WHERE Email__c='test2@yahoo.com' LIMIT 1];
        con.email = userProfileObj2.Email__c;
        con.sendEmailAction();        
        
        test.stopTest();
    }
}