src/objects/Examination__c.object
<CustomObject>
    <description>Details of the Exams</description>
    <fields>
        <fullName>Achievement_Rate__c</fullName>
        <label>Achievement_Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Badge__c</fullName>
        <description>Stores link where the image is located.</description>
        <label>Badge</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Description2__c</fullName>
        <label>Description2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Examination Name</description>
        <label>Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Passing_Rate__c</fullName>
        <description>Passing rate for the exam.</description>
        <label>Passing_Rate</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Promotion_Text__c</fullName>
        <description>Lists related Salesforce.com URLs.</description>
        <label>Promotion_Text</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_ID__c</fullName>
        <description>Lists all questions tagged for the exam.</description>
        <label>Question_ID</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Examination</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Examination_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Examinations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>List of questions used in the examination.</description>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Question_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ModifyExamControl.cls
public class ModifyExamControl 
{

    public List <Examination__c> exam = new List<Examination__c>();
    public List <Question__c> questions = new List<Question__c>();
    public Integer ex {get; set;}
    public Integer quest {get; set;}
    public Integer curQuest {get; set;}
    public Boolean tr {get; set;}
    public List <String> q = new List<String>();
    public Integer mes {get; set;}

 
    public List<SelectOption> getopt()
    {
       exam =  [Select e.Achievement_Rate__c, e.Badge__c, e.Description2__c, e.Id, e.Name__c, e.Passing_Rate__c, e.Promotion_Text__c, e.Question_ID__c from Examination__c e];
       List<selectOption> opt = new list<selectOption>();
       for(integer x=0; x<exam.size(); x++)
       {

       opt.add(new SelectOption (x.format(), exam[x].name__c));
       }
       
          return opt;
    }
    
    public List<SelectOption> getquestpool()
    {
       questions =  [Select q.Question__c, q.ID, q.Name from Question__c q ORDER BY q.Name];
       List<selectOption> opt = new list<selectOption>();
       for(integer x=0; x<questions.size(); x++)
       {
           opt.add(new SelectOption(x.format(), questions[x].Name + '  :  ' + questions[x].question__c));
       }
       
          return opt;
    }
    
   
    
    public pagereference LoadQuestions()
    {
        System.debug('LOAD QUESTIONS');
        mes = 0;
        tr=true;
        q =new List<String>();
        if (exam[ex].Question_ID__c!=null)
            q = exam[ex].Question_ID__c.split(',',-1);
        return null;
    }
    
     public List<SelectOption> getcurrentQuest()
    {
       List<selectOption> opt = new list<selectOption>();
       
       
//       if (q!=null)
//       for(integer x=0; x<q.size(); x++)
//       {
//           opt.add(new SelectOption(x.format(),q[x]));
//       }

       if(q!= null)
       {
           for(integer x=0; x<q.size(); x++)
           {
               List <Question__c> tempList = new List<Question__c>();
               tempList = [Select q.Question__c, q.Name from Question__c q WHERE q.ID = :q[x]];
               System.debug('question ID: ' + q[x]);     
               System.debug('tempList : ' + tempList);                
               opt.add(new SelectOption(x.format(), tempList[0].Name + '  :  ' + tempList[0].Question__c));                         
           } 
           
                     
       }
       
       return opt;
    }
    
    public PageReference add()
    {
        mes = 0;
        for (integer x=0; x<q.size(); x++)
            if(q[x] == questions[quest].ID)
            {
                mes = 1;
                return null;
            }
        q.add(questions[quest].ID);
        return null;
    }
    
    public PageReference remove()
    {
        mes = 0;
        q.remove(curquest);
        return null;
    }
    
    public pagereference save ()
    {
        exam[ex].Question_ID__c = null;
        for(integer x=0; x<q.size(); x++)
        {
            if (x+1 == q.size())
                exam[ex].Question_ID__c+=q[x];
            else
                exam[ex].Question_ID__c+=q[x]+',';
        }
        if (exam[ex].Question_ID__c!=null)
            exam[ex].Question_ID__c=exam[ex].Question_ID__c.replace('null','');
        update exam[ex];
        mes = 2;
        return null;
    }

}