src/objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Confirmed_By__c</fullName>
        <label>Confirmed By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Confirmed_By</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <label>SubType</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Product Order</fullName>
                </value>
                <value>
                    <fullName>Mall Rent</fullName>
                </value>
                <value>
                    <fullName>Permits/Forms</fullName>
                </value>
                <value>
                    <fullName>Salary</fullName>
                </value>
                <value>
                    <fullName>Royalty Fee</fullName>
                </value>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>Clinic Use</fullName>
                </value>
                <value>
                    <fullName>Maintenance</fullName>
                </value>
                <value>
                    <fullName>Flyers</fullName>
                </value>
                <value>
                    <fullName>Mall Event</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Prepaid Load</fullName>
                </value>
                <value>
                    <fullName>Laundry</fullName>
                </value>
                <value>
                    <fullName>Tax</fullName>
                </value>
                <value>
                    <fullName>Cash Advance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Spa Supply</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Operation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>EXP - {0000000}</displayFormat>
        <label>Expense ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Confirmed_By.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Not Confirmed</fullName>
        <default>true</default>
        <label>Not Confirmed</label>
    </customValue>
    <customValue>
        <fullName>Thess</fullName>
    </customValue>
    <customValue>
        <fullName>Lui</fullName>
    </customValue>
    <customValue>
        <fullName>Anna</fullName>
    </customValue>
    <masterLabel>Confirmed By</masterLabel>
</GlobalValueSet>

src/classes/ExpenseController.cls
public class ExpenseController{
    
    public string selectedYear { get; set; }
    public string selectedMonth { get; set; }
    public date selecteddate { get; set; }
    public boolean dayIsConfirmed { get; set; }
    public Expense__c Expense { get; set; }
    public List<Expense__c> expenses { get; set; }
    public decimal total{
        get{
            decimal x =0;
            for(Expense__c e : expenses)
                x+=e.Amount__c;
            return x;
        }
    }
    
    public ExpenseController(){
       // getTodayExpenses();
        dayIsConfirmed = true;
    }
    
    public void createNewExpense(){
        expense = new Expense__c();
        expense.amount__c = 0.0;
    }
    
    public void deleteExpense(){
        string id = Apexpages.currentPage().getParameters().get('expenseid');
        if (id!=null){
            delete [Select Id from Expense__c where Id =: id];
            getTodayExpenses();
        }
    }
    
    public void setSelectedExpense(){
        string id = Apexpages.currentPage().getParameters().get('expenseid');
        if (id!=null){
            List<Expense__c> expenses = [Select Id, Type__c, SubType__c, description__c, amount__c, date__c, Confirmed_By__c  from Expense__c where Id =: id];
            if (expenses.size()>0){
                expense = expenses[0];
            }
            
        }
    }
    
    
    public void getExpenses(integer y, integer m, integer d){
        date mdate = dateTime.newInstance(y,m,d,0,0,0).date();
        if(d==-1){
            expenses = [Select Id, Type__c, SubType__c, description__c, amount__c, date__c, Confirmed_By__c  from Expense__c where Calendar_Year(date__c)=:y and calendar_Month(date__c)=:m order by date__c desc];
        }else{
            
            expenses = [Select Id, Type__c, SubType__c, description__c, amount__c, date__c, Confirmed_By__c  from Expense__c where date__c=:mdate];
        }
        
        if(expenses.size()>0){
            dayIsConfirmed  = expenses[0].Confirmed_By__c==null || expenses[0].Confirmed_By__c =='Not Confirmed' ? false : true;
        }
        selecteddate = d==-1 ? null : mdate;
    }
    
    public void getTodayExpenses(){
        selecteddate = System.today();
        expenses = [Select Id, Type__c, SubType__c, description__c, amount__c, date__c, Confirmed_By__c from Expense__c order by date__c desc];
    }
    
    public void saveExpense(){
        upsert expense;
        getTodayExpenses();
    }
    
     public void getExpensesByMonth(){
        Integer y = Integer.valueOf( Apexpages.currentPage().getParameters().get('y'));
        Integer m= Integer.valueOf( Apexpages.currentPage().getParameters().get('m'));
        
        Date today = System.Today();
        selectedYear = ''+y;
        selectedMonth = ''+m; 
        getExpenses(y,m,-1);
     }
     
     public void getExensesByday(){
        Integer y = Integer.valueOf( Apexpages.currentPage().getParameters().get('y'));
        Integer m= Integer.valueOf( Apexpages.currentPage().getParameters().get('m'));
        Integer d= Integer.valueOf( Apexpages.currentPage().getParameters().get('d'));
        Date today = System.Today();
        selectedYear = ''+y;
        selectedMonth = ''+m; 
        getExpenses(y,m,d);
        
     }

}