src/objects/Job_Application__c.object
<CustomObject>
    <description>Represent&apos;s a candidate&apos;s application to a position</description>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Review Resume</fullName>
                </value>
                <value>
                    <fullName>Phone Screen</fullName>
                </value>
                <value>
                    <fullName>Schedule Interviews</fullName>
                </value>
                <value>
                    <fullName>Extend an Offer</fullName>
                </value>
                <value>
                    <fullName>Hired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Position</fullName>
                    <default>true</default>
                    <label>New Position</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Open - Approved</fullName>
                </value>
                <value>
                    <fullName>Open - Filled</fullName>
                </value>
                <value>
                    <fullName>Closed - Filled</fullName>
                </value>
                <value>
                    <fullName>Closed - Not Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PositionController.cls
public with sharing class PositionController
{

    public PositionController() {
         positions=[Select Id, Name, Status__c from Position__c];
    }

   
    public List<Position__c> positions{get;set;}
    public List<Job_Application__c> positionJobApplications{get;set;}
    public Position__c selectedPosition{get;set;}
    public Id selectedPositionId{get;set;}
   
    public PageReference getDetails()
    {
      PageReference page = ApexPages.CurrentPage();
      String id = page.getparameters().get('cid');
    //  selectedPosition= [Select Id, Name from Position__c where Id=:id];
      
      selectedPositionId= id;
      getJobApplicationByPositionId();
      return page;
    }
    
    public List<Job_Application__c> getJobApplicationByPositionId()
    {
    positionJobApplications=null;
    positionJobApplications=[Select Id, Name, Position__r.Name from Job_Application__c where position__r.Id=: selectedPositionId ];
    return positionJobApplications;
    }
    
   




}