src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Clinic_Use__c</fullName>
        <label>Clinic Use</label>
        <summaryFilterItems>
            <field>Product_Sale__c.Type__c</field>
            <operation>equals</operation>
            <value>Clinic Use</value>
        </summaryFilterItems>
        <summaryForeignKey>Product_Sale__c.Product__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <formula>Stocks__c - Clinic_Use__c  - Sold__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Inventory</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Set__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Set</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Price__c</fullName>
        <label>Retail Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sold__c</fullName>
        <label>Sold</label>
        <summaryFilterItems>
            <field>Product_Sale__c.Type__c</field>
            <operation>equals</operation>
            <value>Sale</value>
        </summaryFilterItems>
        <summaryForeignKey>Product_Sale__c.Product__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Stocks__c</fullName>
        <label>Stocks</label>
        <summarizedField>Product_Delivery__c.Quantity__c</summarizedField>
        <summaryForeignKey>Product_Delivery__c.Product__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Product</label>
    <nameField>
        <displayFormat>PROD-{0000}</displayFormat>
        <label>Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductController.cls
public class ProductController{
    
    public List<Product__c> products { get; set; }
    public string code { get; set; }
    
    public ProductController(){
        
        code = 'lui_anna17';
        //getProductInventory();
    }
    public Integer remaining { get; set; }
    public Integer sold{ get; set; }
    public Integer clinic_use{ get; set; }
    public Integer all{ get; set; }
    public void getProductInventory(){
        remaining =0; sold=0; clinic_use=0; all=0;
        products = [Select Id, Retail_Price__c, Name, Name__c, Sold__c, Stocks__c, Inventory__c, Clinic_Use__c from Product__c order by Is_Set__c desc];
        for(Product__c p : products){
            all+= integer.valueOf(p.Stocks__c);
            sold+= integer.valueOf(p.sold__c);
            clinic_use+= integer.valueOf(p.clinic_use__c);
            remaining += integer.valueOf(p.stocks__c-p.sold__c - p.clinic_use__c); 
        }
        
    }
}