src/objects/User_Examination__c.object
<CustomObject>
    <description>Stores exams a particular user has taken. It also tracks questions not yet answered by a user (if an exam is not completed).</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ongoing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <description>Used to validate user exam session.</description>
        <label>Token</label>
        <type>TextArea</type>
    </fields>
    <label>User Examination</label>
    <nameField>
        <displayFormat>UE-{00000}</displayFormat>
        <label>User_Examination_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Examinations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TakeChallengeController.cls
public class TakeChallengeController 
{
    private String userExamID;
    private String token;
    public Boolean isTokenValid{get; set;}
    
    private User_Examination__c userExam;

    public TakeChallengeController()
    {
        userExamID = ApexPages.currentPage().getParameters().get('userExamID');
        token = ApexPages.currentPage().getParameters().get('token');
        isTokenValid = true;
        
        try
        {
            userExam =  [SELECT CreatedDate, Status__c FROM User_Examination__c WHERE ID = :userExamID AND Token__c = :token];            
        }
        catch( System.QueryException e )
        {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Challenge link has already expired. Please generate a new one.');
            ApexPages.addMessage(myMsg); 
            isTokenValid = false;    
            return;
        }
    }
    
    public PageReference startChallenge() 
    {   
        userExam = [SELECT ID, Token__c FROM User_Examination__c WHERE ID = :userExamID];
        return new PageReference('/apex/examPage?userExamID='+ userExam.ID + '&token='+userExam.Token__c);            
    }
    
}